server:
  port: 8001

spring:
  application:
    name: my-first-service

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: http://192.168.0.2:8761/eureka
