server:
  port: 18084

spring:
  application:
    name: order-service
  zipkin:
    based-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
    probability: 1.0 # zipkin 서버에 100% 전달한다는 의미
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: test1234
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registry-fetch-interval-seconds: 30  #??? ?????? ?????? ???? ??? ??
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    me.kalpha.orderservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus