server:
  port: 8002

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: http://192.168.0.2:8761/eureka

spring:
  application:
    name: my-second-service
