server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/jjd/workspace/spring-learning/native-file-repo
        git:
          uri: https://github.com/kalphageek/spring-cloud-config
#          uri: file:///c:/workspace/spring-learning/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh