server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///home/jjd/workspace/spring-learning/git-local-repo
          uri: git@github.com:kalphageek/spring-cloud-config.git
