server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kalphageek/spring-cloud-config.git
#          uri: file:///c:/workspace/spring-learning/git-local-repo
